### ISSUE TITLE
Unable to run test

### ISSUE THREAD

**Issue by Dx-wmc** [nlm-irp-jianglab/ProkFunFind#6]
Hello, I couldn't wait to use this software as soon as I saw it. However, when I tried to run the test data, it directly encountered an error with the message: `FileNotFoundError: [Errno 2] No such file or directory: 'hmmscan'`. My input command is: `./bin/prokfunfind -f data/Histidine_decarboxylase/config.yaml --gtab data/genome-table.tsv -o tmp`.

**Comment by keithdt** [comment]
Hello, 
Thanks for your interest in using ProkFunFind.
 
It looks like you might not have hmmer installed or available in the environment you are running through. For searches using hidden Markov Models, like this Histidine decarboxylase example data, ProkFunFind uses HMMER to identify homologous sequences. 

For the instructions on how to install HMMER please see the HMMER documentation here: http://hmmer.org/documentation.html
After Installing HMMER, you should then have access to the 'hmmscan' executable and be able to run the search.

**Comment by Dx-wmc** [comment]
It is fine for me to install hmmer. I suggest adding `conda install-c bioconda hmmer` in the installation section.
